### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by thbonk** [Swiftodon/Mastodon.swift#3]
- add target for macOS
- add support for Carthage
- add support for Swift PM

**Comment by moyasine** [comment]
I can't build Mastodon.swift with Carthage

*** Fetching Mastodon.swift
*** Checking out Mastodon.swift at "1.0.1"
*** xcodebuild output can be found in /var/folders/p_/phwjcbg160l_1_xb12bh6h1w0000gn/T/carthage-xcodebuild.10QI57.log
*** Skipped building Mastodon.swift due to the error:
Dependency "Mastodon.swift" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Swiftodon/Mastodon.swift/issues/new

**Comment by DK1DA** [comment]
@moyasine please try `1.1.0` those issue should be fixed there.

**Comment by DK1DA** [comment]
@thbonk I'm closing this issue, w're now supporting macOS, Carthage and SwiftPM should also be working.

**Comment by moyasine** [comment]
I can't still build Mastodon.swift with Carthage...

*** Checking out Mastodon.swift at "1.1.0"
*** xcodebuild output can be found in /var/folders/p_/phwjcbg160l_1_xb12bh6h1w0000gn/T/carthage-xcodebuild.qNwExt.log
carthage(556,0x7000002a0000) malloc: *** error for object 0x7f8376c81ce8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by DK1DA** [comment]
@moyasine could you please look into the `xcodebuild.log`? I've seen this before and IIRC upgrading Carthage resolved the issue.

**Comment by moyasine** [comment]
I resolved this issue. Thank you very much.

**Comment by DK1DA** [comment]
@moyasine how did you resolve it? (Might be helpful for others at some point.)
